# Placeholders:
# %label% - command label

DEFAULT-COLOR: '&8'
TITLE: '&dName Colours'
USAGE: '&cUsage: /%label% <color>'
GUI-SIZE: 18

FORMATTING:
  ITALIC:
    SLOT: 14
  BOLD:
    SLOT: 15
  UNDERLINE:
    SLOT: 16
  RESET:
    SLOT: 17
